/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_if2kmainwindow (void)
{
  GtkWidget *if2kmainwindow;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *hbox2;
  GtkWidget *vbox2;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button6;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *label3;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview2;
  GtkWidget *label4;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview3;
  GtkWidget *label5;

  if2kmainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (if2kmainwindow, "if2kmainwindow");
  gtk_window_set_title (GTK_WINDOW (if2kmainwindow), "if2k Settings");
  gtk_window_set_default_size (GTK_WINDOW (if2kmainwindow), -1, 400);

  vbox1 = gtk_vbox_new (FALSE, 8);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (if2kmainwindow), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 8);

  hbox1 = gtk_hbox_new (FALSE, 10);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 8);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox1), table1, FALSE, TRUE, 0);

  label1 = gtk_label_new ("Server Address:");
  gtk_widget_set_name (label1, "label1");
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  label2 = gtk_label_new ("Password\n");
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_show (entry1);
  gtk_table_attach (GTK_TABLE (table1), entry1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_show (entry2);
  gtk_table_attach (GTK_TABLE (table1), entry2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  button1 = gtk_button_new_with_mnemonic ("Login");
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_box_pack_start (GTK_BOX (hbox1), button1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button1), 8);

  button2 = gtk_button_new_with_mnemonic ("Change Password...");
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_box_pack_start (GTK_BOX (hbox1), button2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button2), 8);

  button3 = gtk_button_new_with_mnemonic ("Apply");
  gtk_widget_set_name (button3, "button3");
  gtk_widget_show (button3);
  gtk_box_pack_end (GTK_BOX (hbox1), button3, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (button3), 8);

  hbox2 = gtk_hbox_new (FALSE, 8);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, TRUE, 8);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 8);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox2, TRUE, TRUE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("Enable Filtering");
  gtk_widget_set_name (checkbutton1, "checkbutton1");
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (vbox2), checkbutton1, FALSE, FALSE, 0);

  checkbutton2 = gtk_check_button_new_with_mnemonic ("Allow Override");
  gtk_widget_set_name (checkbutton2, "checkbutton2");
  gtk_widget_show (checkbutton2);
  gtk_box_pack_start (GTK_BOX (vbox2), checkbutton2, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_mnemonic ("Customize");
  gtk_widget_set_name (button4, "button4");
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (hbox2), button4, FALSE, FALSE, 0);

  button5 = gtk_button_new_with_mnemonic ("Remote Settings");
  gtk_widget_set_name (button5, "button5");
  gtk_widget_show (button5);
  gtk_box_pack_start (GTK_BOX (hbox2), button5, FALSE, FALSE, 0);

  button6 = gtk_button_new_with_mnemonic ("License");
  gtk_widget_set_name (button6, "button6");
  gtk_widget_show (button6);
  gtk_box_pack_start (GTK_BOX (hbox2), button6, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);

  textview1 = gtk_text_view_new ();
  gtk_widget_set_name (textview1, "textview1");
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);

  label3 = gtk_label_new ("Bad URLs");
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);

  textview2 = gtk_text_view_new ();
  gtk_widget_set_name (textview2, "textview2");
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview2);

  label4 = gtk_label_new ("Good URLs");
  gtk_widget_set_name (label4, "label4");
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);

  textview3 = gtk_text_view_new ();
  gtk_widget_set_name (textview3, "textview3");
  gtk_widget_show (textview3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview3);

  label5 = gtk_label_new ("Phrases");
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (if2kmainwindow, if2kmainwindow, "if2kmainwindow");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button1, "button1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button2, "button2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button3, "button3");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button4, "button4");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button5, "button5");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, button6, "button6");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, textview2, "textview2");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, textview3, "textview3");
  GLADE_HOOKUP_OBJECT (if2kmainwindow, label5, "label5");

  return if2kmainwindow;
}

