#include "jdk_world.h"
#include "if2k_settings.h"


jdk_setting_description default_server_settings[] =
{
  {"listen_count", "10", "TCP/IP listen queue size."},
  {"interface","127.0.0.1:8000", "IP address and port to bind to"},
  {"admin_interface","127.0.0.1:8001", "IP address and port to bind to for administration."},
  {"further_proxy","", "Additional HTTP proxy IP address  and port." },
  {"control_port","8001", "TCP/IP port for parent server control, 0 to disable." },
  
  {"cached_settings", "remote_settings.txt", "local file to hold remote settings" },
  {"remote_settings", "", "URL of remote settings" },
  {"remote_update_rate", "60", "update rate in minutes" },  
  
  {"max_retries", "4", "Maximum retries when connecting to external server." },
  {"retry_delay", "100", "Delay in ms before retrying connection to external server." },
  {"use_keepalive", "0", "Use HTTP-Keep-alive." },
  {"enable_login", "1", "Allow http login" },
  {"tunnel_mode", "0", "Use large tunnel." }, 
  {"main_server_url", "", "Parent server URL for remote settings" },
  
#if JDK_IS_UNIX
  {"setuid", "0", "1 to set UID/GID on startup." },
  {"uid", "0", "UID to use." },
  {"use_fork", "0", "Use forking processes instead of threads." },
  {"daemon", "1", "Become a background process." },
  {"pid_dir", ".", "Directory to put PID file in: Blank=none." },
#endif
  {"home", DEFAULT_APP_DIR, "Home directory." },	
  {"name", IF2K_SHORT_SERVICE_NAME, "Name to use for logging." },
  {"log_type", "3", "Logging type: 0=none, 1=syslog, 2=stderr, 3=file." },
  {"log_file", "log.txt", "Logging file name." },
  {"log_detail", "2", "Logging detail level: 0=Errors, 1=Warnings, 2=Notices, 3=Info, 4-8=Debug" },
  {"threads", "50", "Number of threads to use." },
  
  {"custom_404_enable", "0", "Enable customized 'Error 404' message" },
  {"custom_404_url", "", "Remote 'Error 404' message." },
  {"custom_404_cache", "custom_404.html", "Cached 'Error 404' message" },
  
  {"custom_connect_error_enable", "0", "Enable customized 'Connection Error' message" },
  {"custom_connect_error_url", "", "Remote 'Connection Error' message." },
  {"custom_connect_error_cache", "custom_connect_error.html", "Cached 'Connection Error' message" },
  
  {"allowed_client_ips", "0.0.0.0/0.0.0.0", "IP ranges of allowed clients." },
  {"nofilter_client_ips", "", "IP ranges of clients that are never filtered." },
  {"blocked_client_ips", "", "IP ranges of blocked clients." },
  
  // license settings
  {"serial", "demo", "Serial number." },
  {"license_valid", "0", "License is valid." },
  {"license_name", "Demonstration", "Licensed to." },
  {"license_clients", "1", "Max clients." },
  {"license_email", "", "Owner email address." },
  {"license_expires", "0", "expirty time." },
  {"license_validated_serial", "demo", "" },
  // kernel settings
  {"proxy_bypass_urls_file", "bypassproxy.txt", "File of urls that bypass further_proxy." },
  {"proxy_bypass_urls_url", "", "Remote url of urls that bypass further_proxy." },
  {"proxy_bypass_urls_url_cache", "bypassproxy.cache", "Cached remote url of urls that bypass further_proxy" },	 
  
  {"mode_textedit_bad_urls", "1", "" },	 
  {"mode_textedit_good_urls", "1", "" },	 
  {"mode_textedit_phrases", "1", "" },	 
  
  {"good_site_ips", "0.0.0.0/0.0.0.0", "Good webserver IP addresses" },
  {"good_urls_precomp_file", "", "Precompiled good urls." },
  {"good_urls_precomp_url", "", "Remote precompiled good urls." },
  
  {"good_urls_name", "User's good URLs", "Category name." },	 
  {"good_urls_default_enable", "1", "enable default good urls." },	 
  {"good_urls_default", "defaultgoodurls.zip", "Use embedded default good urls." },
  {"good_urls_file_enable", "1", "Good url file enable." },	 
  {"good_urls_file", "goodurls.txt", "Good url file." },
  {"good_urls_url_enable", "0", "Remote good url enable" },	 
  {"good_urls_url", IF2K_REMOTE_DB "goodurls.txt", "Remote good url file." },
  {"good_urls_url_cache", "goodurls.cache", "Cached remote good url file" },	 
  
  {"good_urls1_name", "Good URLs 1", "Category name." },
  {"good_urls1_default_enable", "0", "enable default good urls." },
  {"good_urls1_default", "01goodurl.zip", "Use embedded default good urls." },
  {"good_urls1_file_enable", "0", "Good url file enable." },
  {"good_urls1_file", "01goodurl.txt", "Good url file." },
  {"good_urls1_url_enable", "0", "Remote good url enable" },
  {"good_urls1_url", IF2K_REMOTE_DB "01goodurl.txt", "Remote good url file." },
  {"good_urls1_url_cache", "01goodurl.cache", "Cached remote good url file" },
  
  {"good_urls2_name", "Good URLs 2", "Category name." },
  {"good_urls2_default_enable", "0", "enable default good urls." },
  {"good_urls2_default", "02goodurl.zip", "Use embedded default good urls." },
  {"good_urls2_file_enable", "1", "Good url file enable." },
  {"good_urls2_file", "02goodurl.txt", "Good url file." },
  {"good_urls2_url_enable", "0", "Remote good url enable" },
  {"good_urls2_url", IF2K_REMOTE_DB "02goodurl.txt", "Remote good url file." },
  {"good_urls2_url_cache", "02goodurl.cache", "Cached remote good url file" },
  
  {"good_urls3_name", "Good URLs 3", "Category name." },
  {"good_urls3_default_enable", "0", "enable default good urls." },
  {"good_urls3_default", "03goodurl.zip", "Use embedded default good urls." },
  {"good_urls3_file_enable", "1", "Good url file enable." },
  {"good_urls3_file", "03goodurl.txt", "Good url file." },
  {"good_urls3_url_enable", "0", "Remote good url enable" },
  {"good_urls3_url", IF2K_REMOTE_DB "03goodurl.txt", "Remote good url file." },
  {"good_urls3_url_cache", "03goodurl.cache", "Cached remote good url file" },
  
  {"good_urls4_name", "Good URLs 4", "Category name." },
  {"good_urls4_default_enable", "0", "enable default good urls." },
  {"good_urls4_default", "04goodurl.zip", "Use embedded default good urls." },
  {"good_urls4_file_enable", "1", "Good url file enable." },
  {"good_urls4_file", "04goodurl.txt", "Good url file." },
  {"good_urls4_url_enable", "0", "Remote good url enable" },
  {"good_urls4_url", IF2K_REMOTE_DB "04goodurl.txt", "Remote good url file." },
  {"good_urls4_url_cache", "04goodurl.cache", "Cached remote good url file" },
  
  {"good_urls5_name", "Good URLs 5", "Category name." },
  {"good_urls5_default_enable", "0", "enable default good urls." },
  {"good_urls5_default", "05goodurl.zip", "Use embedded default good urls." },
  {"good_urls5_file_enable", "1", "Good url file enable." },
  {"good_urls5_file", "05goodurl.txt", "Good url file." },
  {"good_urls5_url_enable", "0", "Remote good url enable" },
  {"good_urls5_url", IF2K_REMOTE_DB "05goodurl.txt", "Remote good url file." },
  {"good_urls5_url_cache", "05goodurl.cache", "Cached remote good url file" },
  
  {"bad_site_ips", "", "Bad webserver IP addresses" },	
  {"bad_urls_precomp_file", "", "Precompiled bad urls." },
  {"bad_urls_precomp_url", "", "Remote precompiled bad urls." },
  
  {"bad_urls_name", "User's Bad URLs", "Category name." },
  {"bad_urls_default_enable", "0", "enable default bad urls." },	 	 
  {"bad_urls_default", "", "Use embedded default bad urls." },
  {"bad_urls_file_enable", "1", "enable bad urls." },	 
  {"bad_urls_file", "badurls.txt", "Bad url file." },
  {"bad_urls_url_enable", "0", "Remote good url enable" },	 
  {"bad_urls_url", IF2K_REMOTE_DB "badurls.txt", "Remote bad url file." },
  {"bad_urls_url_cache", "badurls.cache", "Cached remote bad url file." },
  
  {"bad_urls1_name", "Pornography URLs", "Category name." },
  {"bad_urls1_default_enable", "1", "enable default bad urls." },
  {"bad_urls1_default", "01badurl.zip", "Use embedded default bad urls." },
  {"bad_urls1_file_enable", "1", "enable bad urls." },
  {"bad_urls1_file", "01badurl.txt", "Bad url file." },
  {"bad_urls1_url_enable", "0", "Remote good url enable" },
  {"bad_urls1_url", IF2K_REMOTE_DB "01badurl.txt", "Remote bad url file." },
  {"bad_urls1_url_cache", "01badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls2_name", "Violence, Gore URLs", "Category name." },
  {"bad_urls2_default_enable", "1", "enable default bad urls." },
  {"bad_urls2_default", "02badurl.zip", "Use embedded default bad urls." },
  {"bad_urls2_file_enable", "1", "enable bad urls." },
  {"bad_urls2_file", "02badurl.txt", "Bad url file." },
  {"bad_urls2_url_enable", "0", "Remote good url enable" },
  {"bad_urls2_url", IF2K_REMOTE_DB "02badurl.txt", "Remote bad url file." },
  {"bad_urls2_url_cache", "02badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls3_name", "Hate URLs", "Category name." },
  {"bad_urls3_default_enable", "1", "enable default bad urls." },
  {"bad_urls3_default", "03badurl.zip", "Use embedded default bad urls." },
  {"bad_urls3_file_enable", "1", "enable bad urls." },
  {"bad_urls3_file", "03badurl.txt", "Bad url file." },
  {"bad_urls3_url_enable", "0", "Remote good url enable" },
  {"bad_urls3_url", IF2K_REMOTE_DB "03badurl.txt", "Remote bad url file." },
  {"bad_urls3_url_cache", "03badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls4_name", "Casinos/Gambling URLs", "Category name." },
  {"bad_urls4_default_enable", "1", "enable default bad urls." },
  {"bad_urls4_default", "04badurl.zip", "Use embedded default bad urls." },
  {"bad_urls4_file_enable", "1", "enable bad urls." },
  {"bad_urls4_file", "04badurl.txt", "Bad url file." },
  {"bad_urls4_url_enable", "0", "Remote good url enable" },
  {"bad_urls4_url", IF2K_REMOTE_DB "04badurl.txt", "Remote bad url file." },
  {"bad_urls4_url_cache", "04badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls5_name", "Bad URLs 5", "Category name." },
  {"bad_urls5_default_enable", "0", "enable default bad urls." },
  {"bad_urls5_default", "05badurl.zip", "Use embedded default bad urls." },
  {"bad_urls5_file_enable", "1", "enable bad urls." },
  {"bad_urls5_file", "05badurl.txt", "Bad url file." },
  {"bad_urls5_url_enable", "0", "Remote good url enable" },
  {"bad_urls5_url", IF2K_REMOTE_DB "05badurl.txt", "Remote bad url file." },
  {"bad_urls5_url_cache", "05badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls6_name", "Bad URLs 6", "Category name." },
  {"bad_urls6_default_enable", "0", "enable default bad urls." },
  {"bad_urls6_default", "06badurl.zip", "Use embedded default bad urls." },
  {"bad_urls6_file_enable", "1", "enable bad urls." },
  {"bad_urls6_file", "06badurl.txt", "Bad url file." },
  {"bad_urls6_url_enable", "0", "Remote good url enable" },
  {"bad_urls6_url", IF2K_REMOTE_DB "06badurl.txt", "Remote bad url file." },
  {"bad_urls6_url_cache", "06badurl.cache", "Cached remote bad url file." },
  
  {"bad_urls7_name", "Bad URLs 7", "Category name." },
  {"bad_urls7_default_enable", "0", "enable default bad urls." },
  {"bad_urls7_default", "07badurl.zip", "Use embedded default bad urls." },
  {"bad_urls7_file_enable", "1", "enable bad urls." },
  {"bad_urls7_file", "07badurl.txt", "Bad url file." },
  {"bad_urls7_url_enable", "0", "Remote good url enable" },
  {"bad_urls7_url", IF2K_REMOTE_DB "07badurl.txt", "Remote bad url file." },
  {"bad_urls7_url_cache", "07badurl.cache", "Cached remote bad url file." },
  
  {"bad_phrases_precomp_file", "", "Precompiled bad phrases." },
  {"bad_phrases_precomp_url", "", "Remote precompiled bad phrases." },
  
  {"bad_phrases_name", "User's Bad Phrases", "Category name." },	 
  {"bad_phrases_default_enable", "0", "enable default bad phrases." },	 	 	 
  {"bad_phrases_default", "", "Use embedded default bad phrases." },
  {"bad_phrases_file_enable", "1", "Bad phrases file enable" },	 
  {"bad_phrases_file", "badphrases.txt", "Bad phrases file." },
  {"bad_phrases_url_enable", "0", "Bad phrases url enable" },	 	 
  {"bad_phrases_url", IF2K_REMOTE_DB "badphrases.txt", "Remote bad phrases file." },
  {"bad_phrases_url_cache", "badphrases.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases1_name", "'Pornography' Bad Phrases", "Category name." },
  {"bad_phrases1_default_enable", "1", "enable default bad phrases." },
  {"bad_phrases1_default", "01badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases1_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases1_file", "01badphr.txt", "Bad phrases file." },
  {"bad_phrases1_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases1_url", IF2K_REMOTE_DB "01badphr.txt", "Remote bad phrases file." },
  {"bad_phrases1_url_cache", "01badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases2_name", "'Violence/Gore' Bad Phrases", "Category name." },
  {"bad_phrases2_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases2_default", "02badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases2_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases2_file", "02badphr.txt", "Bad phrases file." },
  {"bad_phrases2_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases2_url", IF2K_REMOTE_DB "02badphr.txt", "Remote bad phrases file." },
  {"bad_phrases2_url_cache", "02badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases3_name", "'Hate' Bad Phrases", "Category name." },
  {"bad_phrases3_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases3_default", "03badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases3_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases3_file", "03badphr.txt", "Bad phrases file." },
  {"bad_phrases3_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases3_url", IF2K_REMOTE_DB "03badphr.txt", "Remote bad phrases file." },
  {"bad_phrases3_url_cache", "03badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases4_name", "Casinos", "Category name." },
  {"bad_phrases4_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases4_default", "04badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases4_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases4_file", "04badphr.txt", "Bad phrases file." },
  {"bad_phrases4_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases4_url", IF2K_REMOTE_DB "04badphr.txt", "Remote bad phrases file." },
  {"bad_phrases4_url_cache", "04badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases5_name", "Bad Phrases 5", "Category name." },
  {"bad_phrases5_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases5_default", "05badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases5_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases5_file", "05badphr.txt", "Bad phrases file." },
  {"bad_phrases5_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases5_url", IF2K_REMOTE_DB "05badphr.txt", "Remote bad phrases file." },
  {"bad_phrases5_url_cache", "05badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases6_name", "Bad Phrases 6", "Category name." },
  {"bad_phrases6_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases6_default", "06badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases6_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases6_file", "06badphr.txt", "Bad phrases file." },
  {"bad_phrases6_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases6_url", IF2K_REMOTE_DB "06badphr.txt", "Remote bad phrases file." },
  {"bad_phrases6_url_cache", "06badphr.cache", "Cached remote bad phrases file." },
  
  {"bad_phrases7_name", "Bad Phrases 7", "Category name." },
  {"bad_phrases7_default_enable", "0", "enable default bad phrases." },
  {"bad_phrases7_default", "07badphr.zip", "Use embedded default bad phrases." },
  {"bad_phrases7_file_enable", "1", "Bad phrases file enable" },
  {"bad_phrases7_file", "07badphr.txt", "Bad phrases file." },
  {"bad_phrases7_url_enable", "0", "Bad phrases url enable" },
  {"bad_phrases7_url", IF2K_REMOTE_DB "07badphr.txt", "Remote bad phrases file." },
  {"bad_phrases7_url_cache", "07badphr.cache", "Cached remote bad phrases file." },
  
  {"censor_phrases_name", "User's Censored Phrases", "Category name." },	 
  {"censor_phrases_default_enable", "0", "enable default censored phrases." },	 	 	 
  {"censor_phrases_default", "", "Use embedded default censored phrases." },
  {"censor_phrases_file_enable", "1", "Censored phrases file enable" },	 
  {"censor_phrases_file", "censorphrases.txt", "Censored phrases file." },
  {"censor_phrases_url_enable", "0", "Censored phrases url enable" },	 	 
  {"censor_phrases_url", IF2K_REMOTE_DB "censorphrases.txt", "Remote censored phrases file." },
  {"censor_phrases_url_cache", "censorphrases.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases1_name", "'Pornography' Censored Phrases", "Category name." },
  {"censor_phrases1_default_enable", "1", "enable default censored phrases." },
  {"censor_phrases1_default", "01censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases1_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases1_file", "01censorphr.txt", "Censored phrases file." },
  {"censor_phrases1_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases1_url", IF2K_REMOTE_DB "01censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases1_url_cache", "01censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases2_name", "'Violence/Gore' Censored Phrases", "Category name." },
  {"censor_phrases2_default_enable", "1", "enable default censored phrases." },
  {"censor_phrases2_default", "02censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases2_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases2_file", "02censorphr.txt", "Censored phrases file." },
  {"censor_phrases2_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases2_url", IF2K_REMOTE_DB "02censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases2_url_cache", "02censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases3_name", "'Hate' Censored Phrases", "Category name." },
  {"censor_phrases3_default_enable", "1", "enable default censored phrases." },
  {"censor_phrases3_default", "03censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases3_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases3_file", "03censorphr.txt", "Censored phrases file." },
  {"censor_phrases3_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases3_url", IF2K_REMOTE_DB "03censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases3_url_cache", "03censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases4_name", "'Casinos/Gambling' Censored Phrases", "Category name." },
  {"censor_phrases4_default_enable", "1", "enable default censored phrases." },
  {"censor_phrases4_default", "04censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases4_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases4_file", "04censorphr.txt", "Censored phrases file." },
  {"censor_phrases4_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases4_url", IF2K_REMOTE_DB "04censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases4_url_cache", "04censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases5_name", "Censored Phrases 5", "Category name." },
  {"censor_phrases5_default_enable", "0", "enable default censored phrases." },
  {"censor_phrases5_default", "05censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases5_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases5_file", "05censorphr.txt", "Censored phrases file." },
  {"censor_phrases5_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases5_url", IF2K_REMOTE_DB "05censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases5_url_cache", "05censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases6_name", "Censored Phrases 6", "Category name." },
  {"censor_phrases6_default_enable", "0", "enable default censored phrases." },
  {"censor_phrases6_default", "06censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases6_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases6_file", "06censorphr.txt", "Censored phrases file." },
  {"censor_phrases6_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases6_url", IF2K_REMOTE_DB "06censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases6_url_cache", "06censorphr.cache", "Cached remote censored phrases file." },
  
  {"censor_phrases7_name", "Censored Phrases 7", "Category name." },
  {"censor_phrases7_default_enable", "0", "enable default censored phrases." },
  {"censor_phrases7_default", "07censorphr.zip", "Use embedded default censored phrases." },
  {"censor_phrases7_file_enable", "1", "Censored phrases file enable" },
  {"censor_phrases7_file", "07censorphr.txt", "Censored phrases file." },
  {"censor_phrases7_url_enable", "0", "Censored phrases url enable" },
  {"censor_phrases7_url", IF2K_REMOTE_DB "07censorphr.txt", "Remote censored phrases file." },
  {"censor_phrases7_url_cache", "07censorphr.cache", "Cached remote censored phrases file." },
  
  {"good_newsgroups_name", "User's Good Newsgroups", "Category name." },	 
  {"good_newsgroups_default_enable", "0", "enable default good newsgroups." },	 	 	 
  {"good_newsgroups_default", "", "Use embedded default good newsgroups." },
  {"good_newsgroups_file_enable", "1", "good newsgroups file enable" },	 
  {"good_newsgroups_file", "goodnewsgroups.txt", "good newsgroups file." },
  {"good_newsgroups_url_enable", "0", "good newsgroups url enable" },	 	 
  {"good_newsgroups_url", IF2K_REMOTE_DB "goodnewsgroups.txt", "Remote good newsgroups file." },
  {"good_newsgroups_url_cache", "goodnewsgroups.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups1_name", "Good Newsgroups 1", "Category name." },
  {"good_newsgroups1_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups1_default", "01goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups1_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups1_file", "01goodnews.txt", "good newsgroups file." },
  {"good_newsgroups1_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups1_url", IF2K_REMOTE_DB "01goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups1_url_cache", "01goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups2_name", "Good Newsgroups 2", "Category name." },
  {"good_newsgroups2_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups2_default", "02goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups2_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups2_file", "02goodnews.txt", "good newsgroups file." },
  {"good_newsgroups2_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups2_url", IF2K_REMOTE_DB "02goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups2_url_cache", "02goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups3_name", "Good Newsgroups 3", "Category name." },
  {"good_newsgroups3_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups3_default", "03goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups3_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups3_file", "03goodnews.txt", "good newsgroups file." },
  {"good_newsgroups3_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups3_url", IF2K_REMOTE_DB "03goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups3_url_cache", "03goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups4_name", "Good Newsgroups 4", "Category name." },
  {"good_newsgroups4_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups4_default", "04goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups4_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups4_file", "04goodnews.txt", "good newsgroups file." },
  {"good_newsgroups4_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups4_url", IF2K_REMOTE_DB "04goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups4_url_cache", "04goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups5_name", "Good Newsgroups 5", "Category name." },
  {"good_newsgroups5_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups5_default", "05goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups5_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups5_file", "05goodnews.txt", "good newsgroups file." },
  {"good_newsgroups5_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups5_url", IF2K_REMOTE_DB "05goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups5_url_cache", "05goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups6_name", "Good Newsgroups 6", "Category name." },
  {"good_newsgroups6_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups6_default", "06goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups6_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups6_file", "06goodnews.txt", "good newsgroups file." },
  {"good_newsgroups6_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups6_url", IF2K_REMOTE_DB "06goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups6_url_cache", "06goodnews.cache", "Cached remote good newsgroups file." },
  
  {"good_newsgroups7_name", "Good Newsgroups 7", "Category name." },
  {"good_newsgroups7_default_enable", "0", "enable default good newsgroups." },
  {"good_newsgroups7_default", "07goodnews.zip", "Use embedded default good newsgroups." },
  {"good_newsgroups7_file_enable", "1", "good newsgroups file enable" },
  {"good_newsgroups7_file", "07goodnews.txt", "good newsgroups file." },
  {"good_newsgroups7_url_enable", "0", "good newsgroups url enable" },
  {"good_newsgroups7_url", IF2K_REMOTE_DB "07goodnews.txt", "Remote good newsgroups file." },
  {"good_newsgroups7_url_cache", "07goodnews.cache", "Cached remote good newsgroups file." },
  
  
  {"bad_newsgroups_name", "User's Bad Newsgroups", "Category name." },	 
  {"bad_newsgroups_default_enable", "0", "enable default bad newsgroups." },	 	 	 
  {"bad_newsgroups_default", "", "Use embedded default bad newsgroups." },
  {"bad_newsgroups_file_enable", "1", "bad newsgroups file enable" },	 
  {"bad_newsgroups_file", "badnewsgroups.txt", "bad newsgroups file." },
  {"bad_newsgroups_url_enable", "0", "bad newsgroups url enable" },	 	 
  {"bad_newsgroups_url", IF2K_REMOTE_DB "badnewsgroups.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups_url_cache", "badnewsgroups.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups1_name", "'Pornography' Bad Newsgroups", "Category name." },
  {"bad_newsgroups1_default_enable", "1", "enable default bad newsgroups." },
  {"bad_newsgroups1_default", "01badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups1_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups1_file", "01badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups1_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups1_url", IF2K_REMOTE_DB "01badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups1_url_cache", "01badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups2_name", "'Violence/Gore' Bad Newsgroups", "Category name." },
  {"bad_newsgroups2_default_enable", "1", "enable default bad newsgroups." },
  {"bad_newsgroups2_default", "02badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups2_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups2_file", "02badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups2_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups2_url", IF2K_REMOTE_DB "02badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups2_url_cache", "02badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups3_name", "'Hate' Bad Newsgroups", "Category name." },
  {"bad_newsgroups3_default_enable", "1", "enable default bad newsgroups." },
  {"bad_newsgroups3_default", "03badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups3_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups3_file", "03badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups3_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups3_url", IF2K_REMOTE_DB "03badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups3_url_cache", "03badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups4_name", "'Casinos/Gambling' Bad Newsgroups", "Category name." },
  {"bad_newsgroups4_default_enable", "1", "enable default bad newsgroups." },
  {"bad_newsgroups4_default", "04badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups4_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups4_file", "04badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups4_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups4_url", IF2K_REMOTE_DB "04badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups4_url_cache", "04badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups5_name", "Bad Newsgroups 5", "Category name." },
  {"bad_newsgroups5_default_enable", "0", "enable default bad newsgroups." },
  {"bad_newsgroups5_default", "05badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups5_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups5_file", "05badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups5_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups5_url", IF2K_REMOTE_DB "05badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups5_url_cache", "05badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups6_name", "Bad Newsgroups 6", "Category name." },
  {"bad_newsgroups6_default_enable", "0", "enable default bad newsgroups." },
  {"bad_newsgroups6_default", "06badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups6_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups6_file", "06badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups6_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups6_url", IF2K_REMOTE_DB "06badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups6_url_cache", "06badnews.cache", "Cached remote bad newsgroups file." },
  
  {"bad_newsgroups7_name", "Bad Newsgroups 7", "Category name." },
  {"bad_newsgroups7_default_enable", "0", "enable default bad newsgroups." },
  {"bad_newsgroups7_default", "07badnews.zip", "Use embedded default bad newsgroups." },
  {"bad_newsgroups7_file_enable", "1", "bad newsgroups file enable" },
  {"bad_newsgroups7_file", "07badnews.txt", "bad newsgroups file." },
  {"bad_newsgroups7_url_enable", "0", "bad newsgroups url enable" },
  {"bad_newsgroups7_url", IF2K_REMOTE_DB "07badnews.txt", "Remote bad newsgroups file." },
  {"bad_newsgroups7_url_cache", "07badnews.cache", "Cached remote bad newsgroups file." },
  
  
  {"url_loggers", "3", "Number of logging units." },
  
  {"loggerA_type", "file", "Type of logger A {none,file,socket,cgi,mail}." },
  {"loggerA_enable", "0", "Enable logger A" },	 
  {"loggerA_log_override", "1", "Enable logging of urls accessed via override." },	 
  {"loggerA_file", "violations.txt", "Destination file name." },
  {"loggerA_level_0", "1", "Enable level 0 logging (unknown sites)." },
  {"loggerA_level_1", "1", "Enable level 1 logging (known good sites)." },
  {"loggerA_level_2", "1", "Enable level 2 logging (known bad sites)." },
  {"loggerA_ignore_images", "1", "1=Don't log URLs of images." },
  
  {"loggerB_type", "mail", "Type of logger B {none,file,socket,cgi,mail}." },	
  {"loggerB_enable", "0", "Enable logger B" },
  {"loggerB_log_override", "1", "Enable logging of urls accessed via override." },
  {"loggerB_level_0", "1", "Enable level 0 logging (unknown sites)." },
  {"loggerB_level_1", "1", "Enable level 1 logging (known good sites)." },
  {"loggerB_level_2", "1", "Enable level 2 logging (known bad sites)." },	
  {"loggerB_ignore_images", "1", "1=Don't log URLs of images." },	
  {"loggerB_smtp_server", "", "smtp server." },	
  {"loggerB_smtp_helo", "localhost", "domain name identification for smtp." },	
  {"loggerB_mail_from", "<>", "send mail from email address." },
  {"loggerB_mail_to", "<>", "send mail from email address." },	
  {"loggerB_mail_subject", "Filter notification", "send mail subject line." },
  {"loggerB_mail_minutes", "1", "Time to send out mail in minutes"  },
  
  {"loggerC_type", "cgi", "Type of logger C {none,file,socket,cgi,mail}." },	
  {"loggerC_enable", "0", "Enable logger C" },
  {"loggerC_log_override", "1", "Enable logging of urls accessed via override." },
  {"loggerC_level_0", "1", "Enable level 0 logging (unknown sites)." },
  {"loggerC_level_1", "1", "Enable level 1 logging (known good sites)." },
  {"loggerC_level_2", "1", "Enable level 2 logging (known bad sites)." },	
  {"loggerC_ignore_images", "1", "1=Don't log URLs of images." },	
  {"loggerC_url", "client-log.cgi?url=", "cgi url pattern" },	
  {"loggerC_proxy", "", "proxy server to use for cgi" },
  
  
  
  
  //
  {"block_unknown", "0", "1=block sites that are not known good." },
  {"block_bad", "1", "0=log but do not block bad sites." },
  {"allow_override", "0", "1=allow client to override blocking." },
  {"override_timeout", "10", "Timeout for override mode in minutes."},
  {"override_unknown_only", "0", "Enable override on unknown sites only."},
  {"override_password", "", "Password to use for override." },
#if IF2K_USE_ADMIN_NAME
  {"admin_username", "admin", "user name for administration"},
#endif
  {"admin_password", "password", "password for administration"},
#if IF2K_USE_ADMIN_NAME
  {"secret_username", "if2k_svc", "Secret username" },
#endif	 
  {"secret_password", "1nternetfilter", "Secret password" },
  
  {"use_internal_blocked_page", "1", "Use internally generated blocked page" },
  {"blocked_page", "http://www.internetfilter.com/", "URL to redirect to when blocking." },
  {"fancy_blocked_page", "1", "0=plain url. 1=cgi script." },	 	 
  {"blocked_page_title", "Blocked by the Internet Filter", ""},
  {"blocked_page_link", "http://www.internetfilter.com/", ""},
  {"blocked_page_image", "blocked1.jpg", "" },
  {"blocked_page_override_url", "/override.cgi?" },
  
  {"mode_ifonly", "0", "IF-Only features" },
  {"mode_expert", "0", "Expert adminstrator mode" },
  {"mode_server", "0", "IF-Server features" },   
  {"mode_demo", "1", "Demonstration Mode" },   	
  
  {"text_font", "face=\"Times New Roman;Times\"", "font to use in web admin pages"},
  {"text_css", "", "html style sheet info for header"},
  {"text_right_to_left", "0" },
  {"text_body_options", "text=\"#000000\" bgcolor=\"#FFFFFF\" link=\"#3333FF\" vlink=\"#3366FF\" alink=\"#000099\" " },
  
  {"text_404_page_errormsg", "error 404: file not found", "Text to display for 404 page." },
  
  {"text_loginmsg", "click here to go to the administrator login page", "Text to display for 404 page login link." },
  {"text_loginlink", "/", "Relative URL for the 404 page login link." },
  
  {"text_product_title1", "the internet filter ", "Product name displayed in web administration." },
  {"text_product_homepage", "http://www.internetfilter.com/", "link to the filters homepage." },
  {"text_product_logo", "/barbwire.jpg" },
  {"text_product_links", "1" },
  
  {"text_block_invalid", "Your Internet Filter license is invalid" },
  {"text_block_info1", "Your request for the document at " },
  {"text_block_info2", "has been blocked " },
  {"text_block_info3", "The administrator of this system may be notified about this violation." },
  {"text_block_reason1", "because it is labelled as a bad website." },
  {"text_block_reason2", "because it is not known to be a good website." },
  {"text_block_reason3", "because the content on the page matched a known bad phrase :" },
  {"text_block_reason4", "because the content you sent matched a known bad phrase" },
  {"text_block_override", "You may temporarily override this block by " },
  {"text_block_override_click", "clicking here" },
  {"text_block_override_warn", "However, all your web accesses will be sent to the administrator." },
  
  {"text_login_title", "administrator login"},
  {"text_login_username", "user name:" },
  {"text_login_password", "password:" },
  {"text_login_error", "session error - you must login again or <br>you must press 'refresh' on your web browser when you are at the login page." },
  {"text_login_reject", "incorrect username or password" },
  
  {"text_filter_settings_title", "filter settings" },
  {"text_filter_settings_header", "filter settings" },
  {"text_filter_settings_ok", "ok" },
  {"text_set_demo", "Your new settings are now in use - however your license is either not valid or the filter is in demonstration mode." },
  {"text_set_good", "Your new settings are now in use" },
  
  {"text_connection_error", "connection error" },
  {"text_connection_error_description", "the server you requested is not currently available" },
  
  {"text_bad_request_error", "error: incorrectly formed request" },
  {"text_edit_good_urls_title", "Good URLs List" },
  
  {"if2k_version", IF2K_VERSION_STRING },
  {"lua_command", "" },
  {0,0}
};



